In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [2]:
data = pd.read_csv("dataset/heart_disease_uci.csv")

data.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [3]:
data = data.drop("id", axis=1)

In [4]:
X = data.drop("num", axis=1)

y = data["num"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [6]:
numeric_features = X.select_dtypes(
    include=["int64","float64"]
).columns

categorical_features = X.select_dtypes(
    include=["object","bool"]
).columns

In [7]:
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [8]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [9]:
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", RandomForestClassifier(random_state=42))
    ]
)

In [10]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['sex', 'dataset', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal'], dtype='object'))])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [11]:
prediction = model.predict(X_test)

In [12]:
accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy)

Accuracy: 0.5815217391304348

In [13]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83        82
           1       0.56      0.57      0.56        53
           2       0.11      0.09      0.10        22
           3       0.15      0.14      0.15        21
           4       0.00      0.00      0.00         6

    accuracy                           0.58       184
   macro avg       0.32      0.34      0.33       184
weighted avg       0.54      0.58      0.56       184

c:\Users\malho\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\malho\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\malho\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [14]:
print(confusion_matrix(y_test, prediction))

[[72  8  2  0  0]
 [13 30  6  4  0]
 [ 3  6  2 11  0]
 [ 3  9  6  3  0]
 [ 0  1  3  2  0]]

In [15]:

from sklearn.model_selection import RandomizedSearchCV

In [16]:
param_grid = {
    "classifier__n_estimators": [100,200,300,500,700],
    "classifier__max_depth": [5,10,15,20,None],
    "classifier__min_samples_split": [2,5,10],
    "classifier__min_samples_leaf": [1,2,4],
    "classifier__max_features": ["sqrt","log2",None]
}

In [17]:
search = RandomizedSearchCV(
    model,
    param_distributions=param_grid,
    n_iter=25,
    cv=5,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1
)

In [18]:
search.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median'))]),
                                                                               Index(['age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca'], dtype='object')),
                                                                              ('cat',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='most_frequent')),
                                                                                               ('onehot',
                                                                                                OneHotEncoder(handle_unk...
                                             ('classifier',
                                              RandomForestClassifier(random_state=42))]),
                   n_iter=25, n_jobs=-1,
                   param_distributions={'classifier__max_depth': [5, 10, 15, 20,
                                                                  None],
                                        'classifier__max_features': ['sqrt',
                                                                     'log2',
                                                                     None],
                                        'classifier__min_samples_leaf': [1, 2,
                                                                         4],
                                        'classifier__min_samples_split': [2, 5,
                                                                          10],
                                        'classifier__n_estimators': [100, 200,
                                                                     300, 500,
                                                                     700]},
                   random_state=42, scoring='accuracy')

In [19]:
print(search.best_params_)

{'classifier__n_estimators': 300, 'classifier__min_samples_split': 5, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'sqrt', 'classifier__max_depth': 15}

In [20]:
best_model = search.best_estimator_

In [21]:
prediction = best_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test,prediction))

Accuracy: 0.6086956521739131

In [23]:
from catboost import CatBoostClassifier

cat_model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function="MultiClass",
    random_state=42,
    verbose=0
)

In [24]:
cat_model.fit(X_train, y_train)

CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=1]="Male": Cannot convert 'Male' to float

In [25]:
prediction = cat_model.predict(X_test)

CatBoostError: There is no trained model to use predict(). Use fit() to train model. Then use this method.

In [26]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, prediction)

print("CatBoost Accuracy:", accuracy)

CatBoost Accuracy: 0.6086956521739131

In [27]:
y.value_counts()

num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64

In [28]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

ValueError: could not convert string to float: 'Male'

In [30]:
from sklearn.ensemble import ExtraTreesClassifier

extra_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", ExtraTreesClassifier(
            n_estimators=500,
            random_state=42
        ))
    ]
)

extra_model.fit(X_train, y_train)

prediction = extra_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, prediction))

Accuracy: 0.5597826086956522

In [31]:
from xgboost import XGBClassifier

xgb_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", XGBClassifier(
            n_estimators=500,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            eval_metric="mlogloss"
        ))
    ]
)

xgb_model.fit(X_train, y_train)

prediction = xgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, prediction))

Accuracy: 0.6195652173913043

In [33]:
XGBClassifier(
    n_estimators=800,
    max_depth=4,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    gamma=0.1,
    random_state=42,
    eval_metric="mlogloss"
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=0.1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=3, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=800, n_jobs=None,
              num_parallel_tree=None, ...)

In [34]:
from sklearn.model_selection import StratifiedKFold

In [36]:
xgb_pipeline.fit(X_train, y_train)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [37]:
xgb_pipeline.fit(X_train, y_train)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [38]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, prediction)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.6195652173913043

In [39]:
results = pd.DataFrame({
    "Model": [
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        60.8,
        61.9
    ]
})

results.sort_values("Accuracy", ascending=False)

           Model  Accuracy
1        XGBoost      61.9
0  Random Forest      60.8

In [43]:
feature_names = xgb_pipeline.named_steps["preprocessor"].get_feature_names_out()

importance = xgb_pipeline.named_steps["classifier"].feature_importances_

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
}).sort_values("Importance", ascending=False)

ValueError: input_features is not equal to feature_names_in_

In [45]:
list(X_train.columns)

['age',
 'sex',
 'dataset',
 'cp',
 'trestbps',
 'chol',
 'fbs',
 'restecg',
 'thalch',
 'exang',
 'oldpeak',
 'slope',
 'ca',
 'thal']

In [ ]:
from xgboost import XGBClassifier

xgb_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", XGBClassifier(
            n_estimators=50,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            eval_metric="mlogloss"
        ))
    ]
)